CI: Makes Release version check more strict

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -170,9 +170,13 @@ jobs:
         then
           VER_TOOL="$("$BIN" --version --quiet)"
           VER_TAG="${GITHUB_REF#refs/*/}"
-          if ! [ "$VER_TOOL" == "$VER_TAG" ]
+          (
+            echo "VER_TOOL: $VER_TOOL"
+            echo "VER_TAG: $VER_TAG"
+          ) | tee /dev/stderr
+          if ! [ "$VER_TOOL" == "$VER_TAG" ] || ! [[ $VER_TOOL =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
           then
-            >&2 echo "ERROR: Version reported by tool ('$VER_TOOL') should equal release tag ('$VER_TAG')!"
+            >&2 echo "ERROR: Version reported by tool ('$VER_TOOL') should equal the release tag ('$VER_TAG')!"
             exit 1
           fi
         fi
