CI: release: Splits version check up into two seprate ones

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -177,10 +177,15 @@ jobs:
             echo "VER_TOOL: $VER_TOOL"
             echo "VER_TAG: $VER_TAG"
           ) | tee /dev/stderr
-          if ! [ "$VER_TOOL" == "$VER_TAG" ] || ! [[ $VER_TOOL =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
+          if ! [ "$VER_TOOL" == "$VER_TAG" ]
           then
             >&2 echo "ERROR: Version reported by tool ('$VER_TOOL') should equal the release tag ('$VER_TAG')!"
             exit 1
+          fi
+          if ! [[ $VER_TOOL =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
+          then
+            >&2 echo "ERROR: Version reported by tool ('$VER_TOOL') should be a semver compatible string, i.e. of the form: "'^[0-9]+\.[0-9]+\.[0-9]+$'
+            exit 2
           fi
         fi
 
